
# PROD
baseurl: "https://www.zharki.net/"

# DEV
# baseurl: "http://localhost:3000/"

languageCode: "en-us"
title: "Zharki News"
# SEO Stuff
canonifyURLs: true
# Custom URLs
permalinks:
  weekly_updates: "/weekly_updates/:year/:month/:title/"
  stories: "/stories/:year/:month/:title/"
