
# ------------------------------------------
#   PROD
# ------------------------------------------

baseurl: "https://www.zharki.net/"

languageCode: "en-us"
title: "ZNN"

# SEO Stuff
canonifyURLs: true
