
# ------------------------------------------
#   PROD
# ------------------------------------------

baseurl: "https://www.zharki.net/"

languageCode: "en-us"
title: "ZNN"

# SEO Stuff
canonifyURLs: true

# Custom URLs
permalinks:
  weekly_updates: "/weekly_updates/:year/:month/:title/"
