backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit

  # -------------------------------------------------------------------------
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI, ie.: "New Post"
    folder: "site/content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Sort Order", name: "sort_order", widget: "number", default: 999, valueType: "int"}

  # -------------------------------------------------------------------------
  #   Streamer
  # -------------------------------------------------------------------------
  - name: "streamer"
    label: "Streamers"
    folder: "site/content/streamers"
    create: true

    fields:
      - {label: "Title", name: "title", widget: "string"} # required?
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Username", name: "username", widget: "string"}
      - {label: "Image", name: "imageUrl", widget: "image", required: false}
      - {label: "Bio", name: "bio", widget: "markdown"}
      - {label: "Notes", name: "notes", widget: "text"}


  # -------------------------------------------------------------------------
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}

      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text

      # Create a custom page for displaying streamers
      - file: "site/content/streamers/_index.md"
        label: "Steamers Page"
        name: "streamer"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}

          # allows you to reference items from another collection
          - label: "Featured Streamer"
            name: "featuredstreamer"
            required: false
            widget: "relation"
            collection: "streamer"
            searchFields: ["name", "bio"]
            valueField: "name"
            displayFields: ["name", "bio"]
          - {label: "Description", name: "description", widget: "text"}
